### ISSUE TITLE
Snap Allowlisting 

### ISSUE THREAD

**Issue by khanti42** [Nomis-cc/nomis-snaps#41]
Hi there, 

We received an allowlisting request for your Snap ! This is great 👍 

In order to move forward we do require you to fill-in the onboarding form. More information - and link to form - here : https://docs.metamask.io/snaps/how-to/get-allowlisted/#prerequisites.

Let me know if you need additional info. 

Looking forward to work with you!

**Comment by khanti42** [comment]
@unchase , @sxlveign

**Comment by SukhachevN** [comment]
@khanti42 Hi! I submitted onboarding form, looking for updates from you, if we need fix anything in this form please inform me.

**Comment by khanti42** [comment]
Hi @SukhachevN , 

I got a new submission for an allowlisting request of Nomis snap version 0.1.5.

But could please fill in the following form : https://feedback.metamask.io/snaps-onboarding/. 
This is to get general information on the builder, not the snap. It's a required step for allowlisting. 

Thank you!

**Comment by SukhachevN** [comment]
@khanti42, done with Snap Builders Onboarding Form, looking forward for next steps!

**Comment by SukhachevN** [comment]
@khanti42 Hello! Any updates about snap allowlisting?
